import * as React from 'react';
import type { Metadata } from "next";
import { notFound } from 'next/navigation';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import theme from '@/theme';
import InitColorSchemeScript from '@mui/material/InitColorSchemeScript';
import { roboto } from '@/app/components/fonts';
import i18nConfig from '@/i18nConfig';
import '@/app/components/global.css';


export const metadata: Metadata = {
  title: {
    template: "%s | MPS Next",
    default: "MPS Next",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {

  
  const { locale } = await params;

  if (!i18nConfig.locales.includes(locale)) {
    notFound();
  };

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={roboto.variable}>
        <InitColorSchemeScript attribute="class" />
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <ThemeProvider theme={theme}>
            {/* CssBaseline kickstart an elegant, consistent, and simple baseline to build upon. */}
            <CssBaseline />
            {children}
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
